apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: auto-ns
  labels:
    app: auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto
  template:
    metadata:
      labels:
        app: auto
    spec:
      containers:
      - name: jenkins-deploy
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        volumeMounts: 
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: { }

---

##### service ########
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: loadbalancer
  selector:
    app: auto
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080